local h = require("tests.support.e2e")

for _, backend in ipairs({ "native", "polling" }) do
  for _, layout in ipairs({ "side-by-side", "inline" }) do
    describe("refresh E2E " .. backend .. " / " .. layout, function()
      local repo, screen
      before_each(function()
        repo = h.repo()
        screen = h.screen(backend, layout)
      end)
      after_each(function()
        if screen then
          screen:close()
          screen = nil
        end
        if repo then
          repo.cleanup()
          repo = nil
        end
      end)

      local function edit(text)
        repo.write_file("a.txt", { "start", text, "context", "end", "tail" })
      end
      local function open(command)
        h.open(screen, repo, command)
      end
      local function unrelated()
        local before = h.checkpoint(screen)
        repo.write_file("background.txt", { "different" })
        h.wait_event(screen, before)
      end

      it("updates unstaged contents even when status and line statistics stay the same", function()
        edit("working-A")
        open()
        h.expect_text(screen, "modified", "working-A")
        edit("working-B")
        h.expect_text(screen, "modified", "working-B")
        assert.equals("working-B", h.panes(screen).modified.lines[2])
      end)

      it("does not replace buffers or move the cursor for an unrelated worktree event", function()
        edit("working-A")
        open()
        screen:exec("vim.api.nvim_win_set_cursor(refresh_session().modified_win, { 4, 0 })")
        local expected = h.panes(screen)
        unrelated()
        h.preserved(screen, expected)
      end)

      it("preserves unsaved working-buffer edits during unrelated notifications", function()
        edit("working-A")
        open()
        screen:exec("vim.api.nvim_set_current_win(refresh_session().modified_win); vim.api.nvim_win_set_cursor(0, { 2, 0 })")
        h.feed(screen, "ccUNSAVED<Esc>")
        h.expect_text(screen, "modified", "UNSAVED")
        unrelated()
        h.expect_text(screen, "modified", "UNSAVED")
        assert.equals("UNSAVED", h.panes(screen).modified.lines[2])
      end)

      it("updates a staged view when the index blob changes", function()
        edit("staged-A")
        repo.git("add a.txt")
        open("CodeDiff --staged")
        h.expect_text(screen, "modified", "staged-A")
        edit("staged-B")
        repo.git("add a.txt")
        h.expect_text(screen, "modified", "staged-B")
      end)

      it("does not redraw a staged view for working-tree-only changes", function()
        edit("staged-A")
        repo.git("add a.txt")
        open("CodeDiff --staged")
        local expected = h.panes(screen)
        local before = h.checkpoint(screen)
        edit("not-staged")
        h.wait_event(screen, before)
        h.preserved(screen, expected)
      end)

      it("switches an unstaged comparison's baseline after staging changes", function()
        edit("index-A")
        repo.git("add a.txt")
        edit("working-B")
        open()
        assert.equals("index-A", h.panes(screen).original.lines[2])
        repo.git("reset HEAD -- a.txt")
        screen:await(function()
          local original = h.panes(screen).original
          return original and original.lines[2] == "base-A"
        end, "unstaged baseline did not return to HEAD")
        h.expect_text(screen, "modified", "working-B")
      end)

      it("refreshes a symbolic revision comparison when only its ref moves", function()
        edit("branch-A")
        repo.git("commit -am branch-A")
        repo.git("branch review-base")
        edit("branch-B")
        repo.git("commit -am branch-B")
        local next_revision = vim.trim(repo.git("rev-parse HEAD"))
        repo.git("reset --hard " .. repo.base)
        edit("working-C")
        open("CodeDiff review-base")
        assert.equals("branch-A", h.panes(screen).original.lines[2])
        repo.git("update-ref refs/heads/review-base " .. next_revision)
        screen:await(function()
          local original = h.panes(screen).original
          return original and original.lines[2] == "branch-B"
        end, "symbolic revision was treated as a fixed SHA")
      end)

      it("keeps following a bare file comparison's symbolic ref after a layout toggle", function()
        repo.git("branch review/topic")
        edit("committed-next")
        repo.git("commit -am next")
        local next_revision = vim.trim(repo.git("rev-parse HEAD"))
        repo.git("reset --hard " .. repo.base)
        edit("working-A")
        open("CodeDiff file review/topic")
        screen:exec("require('codediff.ui.view').toggle_layout(refresh_test.tab)")
        h.idle(screen)
        repo.git("update-ref refs/heads/review/topic " .. next_revision)
        h.expect_text(screen, "original", "committed-next")
      end)

      it("follows HEAD in a bare file comparison after a new commit", function()
        edit("working-A")
        open("CodeDiff file HEAD")
        repo.git("commit -am next")
        screen:await(function()
          return h.panes(screen).original.lines[2] == "working-A"
        end, "bare HEAD comparison stayed pinned")
        h.expect_text(screen, "modified", "working-A")
        assert.equals(0, screen:exec("return #refresh_session().stored_diff_result.changes"))
      end)

      it("refreshes two symbolic revisions without changing the selected file", function()
        repo.git("branch left-ref")
        edit("right-A")
        repo.git("commit -am right-A")
        repo.git("branch right-ref")
        open("CodeDiff left-ref right-ref")
        h.expect_text(screen, "modified", "right-A")
        edit("right-B")
        repo.git("commit -am right-B")
        repo.git("update-ref refs/heads/right-ref HEAD")
        h.expect_text(screen, "modified", "right-B")
      end)

      it("keeps fixed revision comparisons untouched by worktree, index and HEAD changes", function()
        edit("committed-A")
        repo.git("commit -am change-A")
        local changed = vim.trim(repo.git("rev-parse HEAD"))
        open("CodeDiff " .. repo.base .. " " .. changed)
        local expected = h.panes(screen)
        local before = h.checkpoint(screen)
        edit("committed-B")
        repo.git("add a.txt")
        repo.git("commit -m change-B")
        h.wait_event(screen, before)
        h.preserved(screen, expected)
      end)

      it("updates untracked previews without replacing their windows or losing sizes", function()
        repo.write_file("new.txt", { "start", "new-A", "end" })
        h.open(screen, repo, "CodeDiff -- new.txt", "new.txt")
        local before = h.panes(screen)
        repo.write_file("new.txt", { "start", "new-B", "end" })
        h.expect_text(screen, "modified", "new-B")
        local after = h.panes(screen)
        assert.equals(before.modified.buf, after.modified.buf)
        assert.equals(before.modified.win, after.modified.win)
      end)

      it("refreshes the visible deleted-file preview after HEAD moves", function()
        edit("next-base")
        repo.git("commit -am next")
        local next_revision = vim.trim(repo.git("rev-parse HEAD"))
        repo.git("reset --hard " .. repo.base)
        repo.git("rm a.txt")
        open("CodeDiff --staged")
        h.expect_text(screen, "original", "base-A")
        repo.git("update-ref refs/heads/main " .. next_revision)
        h.expect_text(screen, "original", "next-base")
      end)

      it("preserves manual folds and scrolled viewports on unrelated events", function()
        local lines = {}
        for i = 1, 100 do
          lines[i] = "line " .. i
        end
        repo.write_file("a.txt", lines)
        repo.git("commit -am long-file")
        lines[40] = "working-A"
        repo.write_file("a.txt", lines)
        open()
        screen:exec([[
          local win = refresh_session().modified_win
          vim.api.nvim_set_current_win(win)
          vim.wo[win].foldmethod = 'manual'
          vim.cmd('10,20fold')
          vim.api.nvim_win_set_cursor(win, { 40, 0 })
        ]])
        h.feed(screen, "zz")
        h.idle(screen)
        local expected = h.panes(screen)
        local unchanged = h.watch_grid(screen)
        unrelated()
        h.preserved(screen, expected, 200)
        assert.equals(10, screen:exec("return vim.api.nvim_win_call(refresh_session().modified_win, function() return vim.fn.foldclosed(10) end)"))
        unchanged()
      end)

      it("refreshes staged added-file previews when their index content changes", function()
        repo.write_file("new.txt", { "start", "added-A", "end" })
        repo.git("add new.txt")
        h.open(screen, repo, "CodeDiff --staged -- new.txt", "new.txt")
        repo.write_file("new.txt", { "start", "added-B", "end" })
        repo.git("add new.txt")
        h.expect_text(screen, "modified", "added-B")
      end)

      it("refreshes history lists without reopening the selected historical diff", function()
        edit("history-A")
        repo.git("commit -am history-A")
        open("CodeDiff history")
        local expected = h.panes(screen)
        edit("history-B")
        repo.git("commit -am history-B")
        screen:await(function()
          return screen:exec([[
            local s = refresh_session()
            return s.panel and s.panel.data.commits[1].subject == 'history-B'
          ]])
        end, "new commit did not reach history")
        h.preserved(screen, expected)
      end)
    end)
  end
end
