local h = require("tests.support.e2e")
local fixture = require("tests.fixtures.refresh_repo")

for _, backend in ipairs({ "native", "polling" }) do
  for _, layout in ipairs({ "side-by-side", "inline" }) do
    describe("source refresh E2E / " .. backend .. " / " .. layout, function()
      local repo, other_repo, screen
      before_each(function()
        screen = h.screen(backend, layout)
      end)
      after_each(function()
        h.close(screen, repo)
        if other_repo then
          other_repo.cleanup()
        end
        screen, repo, other_repo = nil, nil, nil
      end)

      it("[S01] reloads BOM/CRLF content at a Unicode path without introducing phantom lines", function()
        repo = h.repo()
        local file = "utf8/文件 name.txt"
        repo.write_bytes(file, "\239\187\191开始\r\n已修改\r\n结束\r\n")
        h.open(screen, repo, "CodeDiff file HEAD", file, file)
        h.expect_lines(screen, "original", fixture.files[file])
        h.expect_lines(screen, "modified", { "开始", "已修改", "结束" })
        h.expect_text(screen, "modified", "已修改")
        repo.write_bytes(file, "\239\187\191开始\r\n再次修改\r\n结束\r\n")
        h.expect_lines(screen, "modified", { "开始", "再次修改", "结束" })
        h.expect_text(screen, "modified", "再次修改")
      end)

      it("[S02] keeps refreshed Lua revisions read-only without triggering FileType attachment", function()
        repo = h.repo()
        repo.write_bytes("sample.lua", "local value = 'index-one'\r\nreturn value\r\n")
        repo.command({ "add", "sample.lua" })
        screen:exec([[
          refresh_test.lua_filetypes = {}
          vim.api.nvim_create_autocmd('FileType', { pattern = 'lua', callback = function(ev)
            refresh_test.lua_filetypes[#refresh_test.lua_filetypes + 1] = vim.api.nvim_buf_get_name(ev.buf)
          end })
        ]])
        h.open(screen, repo, "CodeDiff --staged -- sample.lua", "sample.lua")
        h.expect_text(screen, "modified", "index-one")
        repo.write_bytes("sample.lua", "local value = 'index-two'\r\nreturn value\r\n")
        repo.command({ "add", "sample.lua" })
        h.expect_text(screen, "modified", "index-two")
        h.expect_lines(screen, "modified", { "local value = 'index-two'", "return value" })
        local state = screen:exec([[
          local buf = refresh_session().modified_bufnr
          return { readonly = vim.bo[buf].readonly, modifiable = vim.bo[buf].modifiable,
            filetype = vim.bo[buf].filetype, events = refresh_test.lua_filetypes,
            diagnostics = vim.diagnostic.is_enabled({ bufnr = buf }) }
        ]])
        assert.is_true(state.readonly)
        assert.is_false(state.modifiable)
        assert.equals("", state.filetype)
        assert.same({}, state.events)
        assert.is_false(state.diagnostics)
      end)

      it("[S03] preserves a missing final newline across external updates", function()
        repo = h.repo()
        repo.write_bytes("a.txt", "start\none\nend")
        repo.git("commit -am no-final-newline")
        repo.write_bytes("a.txt", "start\ntwo\nend")
        h.open(screen, repo, "CodeDiff file HEAD")
        h.expect_lines(screen, "original", { "start", "one", "end" })
        h.expect_text(screen, "modified", "two")
        repo.write_bytes("a.txt", "start\nthree\nend")
        h.expect_lines(screen, "modified", { "start", "three", "end" })
        h.expect_text(screen, "modified", "three")
        assert.is_false(screen:exec("return vim.bo[refresh_session().modified_bufnr].endofline"))
      end)

      it("[S04] turns an empty staged addition into a populated preview in place", function()
        repo = h.repo()
        repo.write_file("empty-added.txt", {})
        repo.command({ "add", "empty-added.txt" })
        h.open(screen, repo, "CodeDiff --staged -- empty-added.txt", "empty-added.txt")
        h.expect_lines(screen, "modified", { "" })
        local before = h.panes(screen)
        repo.write_file("empty-added.txt", { "now populated" })
        repo.command({ "add", "empty-added.txt" })
        h.expect_text(screen, "modified", "now populated")
        assert.equals(before.modified.win, h.panes(screen).modified.win)
        assert.equals(before.modified.buf, h.panes(screen).modified.buf)
      end)

      it("[S05] a bare comparison follows an empty working file in both directions", function()
        repo = h.repo()
        h.open(screen, repo, "CodeDiff file HEAD", "empty.txt", "empty.txt")
        h.expect_lines(screen, "modified", { "" })
        repo.write_file("empty.txt", { "created content" })
        h.expect_text(screen, "modified", "created content")
        repo.write_file("empty.txt", {})
        h.expect_lines(screen, "modified", { "" })
        h.idle(screen)
        assert.is_false(h.contains(screen, "modified", "created content"))
      end)

      it("[S06] an unstaged renamed file compares against the renamed index path", function()
        repo = h.repo()
        repo.command({ "mv", "rename/source file.txt", "rename/renamed file.txt" })
        repo.replace("rename/renamed file.txt", 3, "working rename")
        h.open(screen, repo, "CodeDiff", "rename/renamed file.txt", "rename/renamed file.txt")
        h.expect_lines(screen, "original", fixture.files["rename/source file.txt"])
        h.expect_text(screen, "modified", "working rename")
        h.action(screen, "view", "toggle_staged_view", "modified")
        h.expect_lines(screen, "modified", fixture.files["rename/source file.txt"])
        h.expect_text(screen, "original", "rename body 2")
      end)

      it("[S07] full-SHA ancestry remains fixed while HEAD and working contents move", function()
        repo = h.repo("history")
        h.open(screen, repo, "CodeDiff file " .. repo.second .. "^")
        h.expect_text(screen, "original", "history-one")
        repo.command({ "reset", "--hard", repo.base })
        h.expect_text(screen, "modified", "base-A")
        h.expect_text(screen, "original", "history-one")
      end)

      it("[S08] a staged symbolic base follows a moved tag without losing index content", function()
        repo = h.repo("history")
        repo.replace("a.txt", 2, "index-three")
        repo.command({ "add", "a.txt" })
        h.open(screen, repo, "CodeDiff --staged fixture/one -- a.txt")
        h.expect_text(screen, "original", "history-one")
        h.expect_text(screen, "modified", "index-three")
        repo.command({ "tag", "-f", "fixture/one", repo.second })
        h.expect_text(screen, "original", "history-two")
        h.expect_text(screen, "modified", "index-three")
      end)

      it("[S09] regular .git-directory repositories use the same refresh behavior", function()
        repo = h.repo(nil, { worktree = false })
        assert.equals(1, vim.fn.isdirectory(repo.path(".git")))
        repo.replace("a.txt", 2, "regular-working")
        h.open(screen, repo, "CodeDiff file HEAD")
        h.expect_text(screen, "modified", "regular-working")
        repo.git("commit -am regular-next")
        h.expect_text(screen, "original", "regular-working")
      end)

      it("[S12] a literal arrow in a filename is not parsed as a rename", function()
        repo = h.repo()
        local file = "literal -> name.txt"
        -- Git can store this path on Windows, but NTFS cannot check it out.
        repo.command({ "config", "core.protectNTFS", "false" })
        repo.write_index(file, { "header", "old value", "tail" })
        repo.command({ "update-index", "--skip-worktree", file })
        repo.command({ "commit", "-m", "literal arrow path" })
        repo.write_index(file, { "header", "new value", "tail" })
        repo.command({ "update-index", "--skip-worktree", file })
        h.open(screen, repo, "CodeDiff", file)
        h.expect_panel(screen, file)
        h.expect_lines(screen, "original", { "header", "old value", "tail" })
        h.expect_text(screen, "modified", "new value")
      end)

      it("[S13] a renamed destination containing an arrow retains its complete path", function()
        repo = h.repo()
        local source, file = "rename/source file.txt", "rename/target -> final.txt"
        repo.command({ "config", "core.protectNTFS", "false" })
        local lines = vim.deepcopy(fixture.files[source])
        lines[3] = "index arrow rename"
        repo.command({ "update-index", "--force-remove", source })
        assert.equals(0, vim.fn.delete(repo.path(source)))
        repo.write_index(file, lines)
        repo.command({ "update-index", "--skip-worktree", file })
        h.open(screen, repo, "CodeDiff", file)
        h.expect_panel(screen, "target -> final.txt")
        h.expect_lines(screen, "original", fixture.files[source])
        h.expect_text(screen, "modified", "index arrow rename")
      end)

      it("[S14] an unborn branch opens staged content against an empty base", function()
        repo = require("tests.support.repository").new({ unborn = true })
        repo.write_file("a.txt", { "unborn-index" })
        repo.command({ "add", "a.txt" })
        h.open(screen, repo, "CodeDiff --staged")
        h.expect_lines(screen, "original", { "" })
        h.expect_text(screen, "modified", "unborn-index")
        repo.write_file("a.txt", { "next-index" })
        repo.command({ "add", "a.txt" })
        h.expect_text(screen, "modified", "next-index")
      end)

      it("[S15] whitespace-ignore policy applies to initial and refreshed comparisons", function()
        repo = h.repo()
        screen:exec("require('codediff').setup({ diff = { ignore_trim_whitespace = true } })")
        repo.replace("a.txt", 2, "  base-A  ")
        h.open(screen, repo, "CodeDiff file HEAD")
        h.expect_text(screen, "modified", "base-A")
        h.action(screen, "view", "next_hunk", "modified", 1)
        assert.equals(1, screen:exec("return vim.api.nvim_win_get_cursor(0)[1]"))
        repo.replace("a.txt", 2, "  changed-A  ")
        h.expect_text(screen, "modified", "changed-A")
        h.idle(screen)
        h.action(screen, "view", "next_hunk", "modified", 1)
        assert.equals(2, screen:exec("return vim.api.nvim_win_get_cursor(0)[1]"))
      end)

      it("[S16] whole-file preview highlighting survives tab suspension and refresh", function()
        repo = h.repo()
        screen:exec("require('codediff').setup({ diff = { highlight_added_deleted_files = true }, highlights = { line_insert = '#123456' } })")
        repo.write_file("preview.txt", { "whole-file-preview", "tail" })
        h.open(screen, repo, "CodeDiff -- preview.txt", "preview.txt")
        h.expect_text(screen, "modified", "whole-file-preview")
        local row, col = h.cell_for(screen, "modified", "whole-file-preview")
        assert.equals(0x123456, screen:highlight(row, col).background)
        screen:command("tabnew")
        screen:command("tabprevious")
        h.idle(screen)
        h.expect_text(screen, "modified", "whole-file-preview")
        row, col = h.cell_for(screen, "modified", "whole-file-preview")
        assert.equals(0x123456, screen:highlight(row, col).background)
      end)

      it("[S17] right-positioned originals retain logical diffget behavior", function()
        repo = h.repo("hunks")
        screen:exec("require('codediff').setup({ diff = { original_position = 'right' } })")
        h.open(screen, repo, "CodeDiff -- hunks.txt", "hunks.txt", "hunks.txt")
        if layout == "side-by-side" then
          assert.is_true(screen:exec([[
            local s = refresh_session()
            return vim.api.nvim_win_get_position(s.original_win)[2] > vim.api.nvim_win_get_position(s.modified_win)[2]
          ]]))
        end
        h.action(screen, "view", "diff_get", "modified", 1)
        h.expect_text(screen, "modified", "base-one")
        assert.equals("working-two", h.panes(screen).modified.lines[12])
      end)

      it("[S18] move detection reaches the renderer and side-by-side alignment key", function()
        repo = h.repo()
        screen:exec("require('codediff').setup({ diff = { compute_moves = true } })")
        repo.write_file(
          "moves.txt",
          { "unchanged_1", "unchanged_2", "unchanged_3", "beta_1", "beta_2", "beta_3", "beta_4", "beta_5", "alpha_1", "alpha_2", "alpha_3", "alpha_4", "alpha_5" }
        )
        h.open(screen, repo, "CodeDiff file HEAD", "moves.txt", "moves.txt")
        assert.is_true(screen:exec("return #refresh_session().stored_diff_result.moves > 0"))
        if layout == "side-by-side" then
          h.reveal(screen, "original", "alpha_1")
          h.action(screen, "view", "align_move")
          screen:await(function()
            local original = h.cell_for(screen, "original", "alpha_1")
            local modified = h.cell_for(screen, "modified", "alpha_1")
            return original ~= nil and original == modified
          end, "paired moved lines did not align on the screen")
          h.feed(screen, "G")
          screen:await(function()
            return screen:exec("local s = refresh_session(); return vim.wo[s.original_win].scrollbind and vim.wo[s.modified_win].scrollbind")
          end)
        else
          h.expect_text(screen, "modified", "alpha_1")
        end
      end)

      it("[S19] --repo resolves and refreshes symbolic refs in the requested repository", function()
        repo = h.repo()
        other_repo = h.repo()
        other_repo.replace("b.txt", 2, "other-base")
        other_repo.commit("other base")
        other_repo.command({ "branch", "review/other" })
        other_repo.replace("b.txt", 2, "other-next")
        local next_revision = other_repo.commit("other next")
        other_repo.command({ "reset", "--hard", "HEAD^" })
        other_repo.replace("b.txt", 2, "other-working")
        local command = "CodeDiff --repo " .. vim.fn.fnameescape(other_repo.dir) .. " review/other -- b.txt"
        h.open(screen, repo, command, "b.txt")
        h.expect_text(screen, "original", "other-base")
        other_repo.command({ "update-ref", "refs/heads/review/other", next_revision })
        h.expect_text(screen, "original", "other-next")
        h.expect_text(screen, "modified", "other-working")
      end)

      it("[S10] SHA-256 repositories resolve and refresh their complete object IDs", function()
        repo = h.repo("history", { object_format = "sha256" })
        assert.equals(64, #repo.base)
        repo.replace("a.txt", 2, "sha256-working")
        h.open(screen, repo, "CodeDiff file HEAD")
        h.expect_text(screen, "modified", "sha256-working")
        repo.git("commit -am sha256-next")
        h.expect_text(screen, "original", "sha256-working")
      end)
    end)
  end
end

for _, layout in ipairs({ "side-by-side", "inline" }) do
  describe("plain source E2E / " .. layout, function()
    local repo, screen
    after_each(function()
      h.close(screen, repo)
      screen, repo = nil, nil
    end)
    it("[S11] compares and refreshes real files with spaces and Unicode names", function()
      repo = h.repo()
      local left, right = "left/文件 name.txt", "right/文件 name.txt"
      repo.write_file(left, { "标题", "LEFT-UTF", "尾部" })
      repo.write_file(right, { "标题", "RIGHT-UTF", "尾部" })
      screen = h.screen("files", layout)
      local command = "CodeDiff file " .. vim.fn.fnameescape(repo.path(left)) .. " " .. vim.fn.fnameescape(repo.path(right))
      h.open(screen, repo, command, right)
      h.expect_text(screen, "modified", "RIGHT-UTF")
      repo.replace(right, 2, "UPDATED-UTF")
      h.expect_text(screen, "modified", "UPDATED-UTF")
      h.expect_lines(screen, "original", { "标题", "LEFT-UTF", "尾部" })
    end)
  end)
end
