local h = require("tests.support.e2e")
local fixture = require("tests.fixtures.refresh_repo")

local function expected(first, second)
  local value = vim.deepcopy(fixture.files["hunks.txt"])
  value[1], value[12] = first or "base-one", second or "base-two"
  return value
end

for _, backend in ipairs({ "native", "polling" }) do
  for _, layout in ipairs({ "side-by-side", "inline" }) do
    describe("hunk actions E2E / " .. backend .. " / " .. layout, function()
      local repo, screen
      before_each(function()
        repo = h.repo("hunks")
        screen = h.screen(backend, layout, {
          diff = { compact_context_lines = 1 },
          highlights = { line_insert = "#102030", char_insert = "#117733", line_delete = "#301020", char_delete = "#aa2233" },
        })
      end)
      after_each(function()
        h.close(screen, repo)
        screen, repo = nil, nil
      end)
      local function open(staged)
        h.open(screen, repo, staged and "CodeDiff --staged -- hunks.txt" or "CodeDiff -- hunks.txt", "hunks.txt", "hunks.txt")
      end

      it("[H01] stages one hunk and removes only its rendered highlight", function()
        open()
        h.expect_text(screen, "modified", "working-one")
        local row, col = h.cell_for(screen, "modified", "working-one")
        assert.equals(0x117733, screen:highlight(row, col).background)
        h.action(screen, "view", "stage_hunk", "modified", 1)
        h.expect_lines(screen, "original", expected("working-one"))
        h.expect_text(screen, "modified", "working-two")
        screen:await(function()
          local r, c = h.cell_for(screen, "modified", "working-one")
          return r and screen:highlight(r, c).background ~= 0x117733
        end, "staged hunk still has an insertion highlight")
        assert.same(expected("working-one"), repo.blob_lines(":0", "hunks.txt"))
        assert.same(expected("working-one", "working-two"), repo.read_file("hunks.txt"))
      end)

      it("[H02] stages both hunks sequentially and enters the staged comparison", function()
        open()
        h.action(screen, "view", "stage_hunk", "modified", 1)
        h.expect_lines(screen, "original", expected("working-one"))
        h.action(screen, "view", "stage_hunk", "modified", 12)
        screen:await(function()
          return screen:exec("return refresh_session().modified_revision == ':0'")
        end, "last staged hunk did not switch comparisons")
        h.expect_text(screen, "modified", "working-two")
        assert.same(expected("working-one", "working-two"), repo.blob_lines(":0", "hunks.txt"))
        assert.equals("", repo.command({ "diff", "--name-only" }))
      end)

      it("[H03] unstages one hunk while preserving the other index change", function()
        repo.command({ "add", "hunks.txt" })
        open(true)
        h.action(screen, "view", "unstage_hunk", "modified", 1)
        h.expect_lines(screen, "modified", expected(nil, "working-two"))
        h.expect_text(screen, "modified", "working-two")
        assert.same(expected(nil, "working-two"), repo.blob_lines(":0", "hunks.txt"))
        assert.same(expected("working-one", "working-two"), repo.read_file("hunks.txt"))
      end)

      it("[H04] confirms discard through the real dialog and preserves the other hunk", function()
        open()
        h.focus(screen, "modified", 1)
        h.confirm(screen, h.key(screen, "view", "discard_hunk"), "Discard hunk", "d")
        h.expect_lines(screen, "modified", expected(nil, "working-two"))
        h.expect_text(screen, "modified", "base-one")
        assert.same(expected(nil, "working-two"), repo.read_file("hunks.txt"))
        assert.same(expected(), repo.blob_lines(":0", "hunks.txt"))
      end)

      it("[H05] cancelling discard leaves buffers, index and working file intact", function()
        open()
        h.focus(screen, "modified", 1)
        local before = h.panes(screen)
        h.confirm(screen, h.key(screen, "view", "discard_hunk"), "Discard hunk", "c")
        h.preserved(screen, before, 100)
        h.expect_text(screen, "modified", "working-one")
        assert.same(expected("working-one", "working-two"), repo.read_file("hunks.txt"))
        assert.same(expected(), repo.blob_lines(":0", "hunks.txt"))
      end)

      it("[H06] discarding a deletion restores the missing lines exactly once", function()
        local value = expected(nil, "working-two")
        table.remove(value, 2)
        table.remove(value, 2)
        repo.write_file("hunks.txt", value)
        open()
        h.focus(screen, "modified", 2)
        h.confirm(screen, h.key(screen, "view", "discard_hunk"), "Discard hunk", "d")
        h.expect_lines(screen, "modified", expected(nil, "working-two"))
        h.expect_text(screen, "modified", "context-02")
        assert.same(expected(nil, "working-two"), repo.read_file("hunks.txt"))
      end)

      it("[H07] discarding a BOF insertion removes only the inserted text", function()
        local value = expected(nil, "working-two")
        table.insert(value, 1, "inserted-at-BOF")
        repo.write_file("hunks.txt", value)
        open()
        h.focus(screen, "modified", 1)
        h.confirm(screen, h.key(screen, "view", "discard_hunk"), "Discard hunk", "d")
        h.expect_lines(screen, "modified", expected(nil, "working-two"))
        h.expect_text(screen, "modified", "base-one")
        assert.same(expected(nil, "working-two"), repo.read_file("hunks.txt"))
      end)

      it("[H08] diffget, undo and redo refresh the view without implicitly saving", function()
        open()
        h.action(screen, "view", "diff_get", "modified", 1)
        h.expect_lines(screen, "modified", expected(nil, "working-two"))
        h.expect_text(screen, "modified", "base-one")
        assert.same(expected("working-one", "working-two"), repo.read_file("hunks.txt"))
        h.feed(screen, "u")
        h.expect_lines(screen, "modified", expected("working-one", "working-two"))
        h.expect_text(screen, "modified", "working-one")
        h.feed(screen, "<C-r>")
        h.expect_lines(screen, "modified", expected(nil, "working-two"))
        h.feed(screen, ":write<CR>")
        assert.same(expected(nil, "working-two"), repo.read_file("hunks.txt"))
      end)

      it("[H09] diffput follows the active layout's editing semantics", function()
        open()
        if layout == "side-by-side" then
          h.action(screen, "view", "diff_put", "original", 1)
          h.expect_lines(screen, "modified", expected(nil, "working-two"))
          h.expect_text(screen, "modified", "base-one")
        else
          h.action(screen, "view", "diff_put", "modified", 1)
          h.expect_lines(screen, "modified", expected("working-one", "working-two"))
          h.expect_text(screen, "modified", "working-one")
        end
        assert.same(expected("working-one", "working-two"), repo.read_file("hunks.txt"))
      end)

      it("[H10] stages unsaved buffer content without replacing it with disk contents", function()
        open()
        h.focus(screen, "modified", 1)
        h.feed(screen, "ccUNSAVED-ONE<Esc>")
        h.expect_text(screen, "modified", "UNSAVED-ONE")
        h.action(screen, "view", "stage_hunk")
        h.expect_lines(screen, "original", expected("UNSAVED-ONE"))
        h.expect_lines(screen, "modified", expected("UNSAVED-ONE", "working-two"))
        assert.same(expected("UNSAVED-ONE"), repo.blob_lines(":0", "hunks.txt"))
        assert.same(expected("working-one", "working-two"), repo.read_file("hunks.txt"))
      end)

      it("[H11] hunk editing still works after changing layout through its keymap", function()
        open()
        h.action(screen, "view", "toggle_layout", "modified", 1)
        screen:await(function()
          return screen:exec("return refresh_session().layout ~= (...) and not refresh_session().refresh.loading", { layout })
        end)
        h.action(screen, "view", "diff_get", "modified", 1)
        h.expect_lines(screen, "modified", expected(nil, "working-two"))
        h.expect_text(screen, "modified", "base-one")
      end)

      it("[H14] the hunk text object selects only the current rendered hunk", function()
        open()
        h.focus(screen, "modified", 1)
        h.feed(screen, "vihy")
        assert.equals("working-one\n", screen:exec([[return vim.fn.getreg('"')]]))
        h.expect_lines(screen, "modified", expected("working-one", "working-two"))
        h.expect_text(screen, "modified", "working-two")
      end)

      it("[H12] compact folds and diff cells survive an unrelated repository update", function()
        open()
        h.action(screen, "view", "toggle_compact", "modified", 1)
        assert.is_true(screen:exec("return vim.api.nvim_win_call(refresh_session().modified_win, function() return vim.fn.foldclosed(5) > 0 end)"))
        h.idle(screen)
        local before, unchanged = h.panes(screen), h.watch_grid(screen)
        local event = h.checkpoint(screen)
        repo.write_file("background.txt", { "background-only" })
        h.wait_event(screen, event)
        h.preserved(screen, before, 150)
        unchanged()
      end)
    end)
  end
end

for _, layout in ipairs({ "side-by-side", "inline" }) do
  describe("manual refresh E2E / " .. layout, function()
    local repo, screen
    after_each(function()
      h.close(screen, repo)
      screen, repo = nil, nil
    end)
    it("[H13] disabled automatic refresh still permits a manual R refresh", function()
      repo = h.repo("hunks")
      screen = h.screen("manual", layout, { explorer = { auto_refresh = false } })
      h.open(screen, repo, "CodeDiff -- hunks.txt", "hunks.txt", "hunks.txt")
      local before = h.panes(screen)
      repo.replace("hunks.txt", 1, "external-one")
      h.preserved(screen, before, 650)
      h.action(screen, "explorer", "refresh", "panel")
      h.expect_lines(screen, "modified", expected("external-one", "working-two"))
      h.expect_text(screen, "modified", "external-one")
    end)
  end)
end
