local h = require("tests.support.e2e")
local fixture = require("tests.fixtures.refresh_repo")

for _, backend in ipairs({ "native", "polling" }) do
  for _, layout in ipairs({ "side-by-side", "inline" }) do
    describe("Explorer actions E2E / " .. backend .. " / " .. layout, function()
      local repo, screen
      before_each(function()
        repo = h.repo("workspace")
        screen = h.screen(backend, layout, { explorer = { width = 38, flatten_dirs = false } })
      end)
      after_each(function()
        h.close(screen, repo)
        screen, repo = nil, nil
      end)
      local function open(command, filename)
        h.open(screen, repo, command or "CodeDiff", filename or "a.txt", filename or "a.txt")
      end

      it("[E01] staging a panel entry advances within its original group", function()
        open("CodeDiff -- b.txt nested/alpha.txt", "b.txt")
        h.panel_cursor(screen, "b.txt", "unstaged")
        h.action(screen, "view", "toggle_stage")
        h.expect_text(screen, "modified", "working-alpha")
        assert.equals("working-B", repo.blob_lines(":0", "b.txt")[2])
        assert.equals("base-alpha", repo.blob_lines(":0", "nested/alpha.txt")[2])
      end)

      it("[E02] staging from a diff pane uses its selected file rather than the panel cursor", function()
        open()
        h.panel_cursor(screen, "b.txt", "unstaged")
        h.action(screen, "view", "toggle_stage", "modified", 2)
        h.expect_text(screen, "modified", "working-B")
        assert.equals("working-A", repo.blob_lines(":0", "a.txt")[2])
        assert.equals("base-B", repo.blob_lines(":0", "b.txt")[2])
      end)

      it("[E03] swaps staged and unstaged comparisons using gS without changing Git", function()
        open()
        h.expect_text(screen, "original", "index-A")
        h.action(screen, "view", "toggle_staged_view", "modified", 2)
        h.expect_text(screen, "original", "base-A")
        h.expect_lines(screen, "modified", { "start", "index-A", "context", "end", "tail" })
        h.action(screen, "view", "toggle_staged_view", "modified", 2)
        h.expect_lines(screen, "modified", { "start", "working-A", "context", "end", "tail" })
        h.expect_text(screen, "original", "index-A")
        assert.equals("index-A", repo.blob_lines(":0", "a.txt")[2])
        assert.equals("working-A", repo.read_file("a.txt")[2])
      end)

      it("[E04] stage-all and unstage-all update both Git and the displayed comparison", function()
        open()
        h.action(screen, "explorer", "stage_all", "panel")
        screen:await(function()
          return screen:exec("return refresh_session().modified_revision == ':0'")
        end)
        h.expect_text(screen, "modified", "working-A")
        assert.equals("", repo.command({ "diff", "--name-only" }))
        h.action(screen, "explorer", "unstage_all", "panel")
        screen:await(function()
          return screen:exec("return refresh_session().modified_revision == nil and not refresh_session().refresh.loading")
        end)
        h.expect_lines(screen, "original", fixture.files["a.txt"])
        h.expect_text(screen, "modified", "working-A")
        assert.equals("", repo.command({ "diff", "--cached", "--name-only" }))
      end)

      it("[E05] stages every file under a tree directory without touching other changes", function()
        screen:exec("require('codediff').setup({ explorer = { view_mode = 'tree' } })")
        open()
        h.panel_cursor(screen, "nested", "unstaged")
        h.action(screen, "view", "toggle_stage")
        screen:await(function()
          return repo.blob_lines(":0", "nested/alpha.txt")[2] == "working-alpha" and repo.blob_lines(":0", "nested/deep/beta.txt")[2] == "working-beta"
        end)
        h.idle(screen)
        h.expect_text(screen, "modified", "working-A")
        assert.equals("index-A", repo.blob_lines(":0", "a.txt")[2])
        assert.equals("base-B", repo.blob_lines(":0", "b.txt")[2])
      end)

      it("[E06] restoring a directory uses the confirmation dialog and preserves other files", function()
        screen:exec("require('codediff').setup({ explorer = { view_mode = 'tree' } })")
        open()
        h.panel_cursor(screen, "nested", "unstaged")
        h.confirm(screen, h.key(screen, "explorer", "restore"), "Discard all changes in", "d")
        h.expect_panel(screen, "nested", false)
        assert.same(fixture.files["nested/alpha.txt"], repo.read_file("nested/alpha.txt"))
        assert.same(fixture.files["nested/deep/beta.txt"], repo.read_file("nested/deep/beta.txt"))
        assert.equals("working-A", repo.read_file("a.txt")[2])
        h.expect_text(screen, "modified", "working-A")
      end)

      it("[E07] cancelling file restore leaves the selected comparison and working file intact", function()
        open()
        h.panel_cursor(screen, "b.txt", "unstaged")
        local before = h.panes(screen)
        h.confirm(screen, h.key(screen, "explorer", "restore"), "Discard changes to", "c")
        h.preserved(screen, before, 100)
        h.expect_panel(screen, "b.txt")
        assert.equals("working-B", repo.read_file("b.txt")[2])
      end)

      it("[E08] deletes an untracked entry through the actual restore confirmation", function()
        open()
        h.panel_cursor(screen, "fresh.txt", "unstaged")
        h.confirm(screen, h.key(screen, "explorer", "restore"), "Delete fresh.txt", "d")
        h.expect_panel(screen, "fresh.txt", false)
        assert.equals(0, vim.fn.filereadable(repo.path("fresh.txt")))
        h.expect_text(screen, "modified", "working-A")
      end)

      it("[E09] group visibility keys affect navigation without changing repository data", function()
        open("CodeDiff -- a.txt b.txt")
        local status = repo.command({ "status", "--porcelain" })
        h.action(screen, "explorer", "toggle_staged", "panel")
        h.expect_panel(screen, "Staged Changes", false)
        h.action(screen, "view", "next_file", "modified")
        h.expect_text(screen, "modified", "working-B")
        h.idle(screen)
        h.action(screen, "view", "prev_file", "modified")
        h.expect_text(screen, "original", "index-A")
        h.action(screen, "explorer", "toggle_staged", "panel")
        h.expect_panel(screen, "Staged Changes")
        assert.equals(status, repo.command({ "status", "--porcelain" }))
      end)

      it("[E10] list/tree toggles and fold keys preserve the diff through a repository update", function()
        open()
        h.action(screen, "explorer", "toggle_view_mode", "panel")
        h.expect_panel(screen, "nested")
        h.panel_cursor(screen, "Changes")
        h.action(screen, "explorer", "fold_close")
        h.expect_panel(screen, "b.txt", false)
        local before, unchanged = h.panes(screen), h.watch_grid(screen)
        local event = h.checkpoint(screen)
        repo.write_file("background.txt", { "changed while folded" })
        h.wait_event(screen, event)
        h.preserved(screen, before, 100)
        unchanged()
        h.expect_panel(screen, "b.txt", false)
        h.panel_cursor(screen, "Changes")
        h.action(screen, "explorer", "fold_open")
        h.expect_panel(screen, "b.txt")
        h.action(screen, "explorer", "toggle_view_mode")
        h.expect_text(screen, "modified", "working-A")
      end)

      it("[E11] auto-open-on-cursor drives file selection through real movement keys", function()
        screen:exec("require('codediff').setup({ explorer = { auto_open_on_cursor = true } })")
        open("CodeDiff -- a.txt b.txt")
        h.panel_cursor(screen, "a.txt", "unstaged")
        h.feed(screen, "j")
        h.expect_text(screen, "modified", "working-B")
        h.idle(screen)
        h.feed(screen, "k")
        h.expect_text(screen, "original", "index-A")
      end)

      it("[E12] a hidden panel shows accumulated list changes when reopened", function()
        open()
        h.action(screen, "view", "toggle_explorer", "modified")
        repo.write_file("visible-later.txt", { "new entry" })
        h.action(screen, "view", "toggle_explorer", "modified")
        h.expect_panel(screen, "visible-later.txt")
        h.expect_text(screen, "modified", "working-A")
      end)

      it("[E13] pathspecs and ignore filters continue to apply after external changes", function()
        screen:exec("require('codediff').setup({ explorer = { file_filter = { ignore = { 'nested/**' } } } })")
        open("CodeDiff -- a.txt nested/alpha.txt")
        h.expect_panel(screen, "alpha.txt", false)
        local event = h.checkpoint(screen)
        repo.replace("nested/alpha.txt", 2, "next-alpha")
        repo.replace("b.txt", 2, "outside-pathspec")
        h.wait_event(screen, event)
        h.expect_panel(screen, "alpha.txt", false)
        h.expect_panel(screen, "b.txt", false)
        h.expect_text(screen, "modified", "working-A")
      end)

      it("[E14] a staged rename retains both paths and ignores unstaged changes", function()
        open("CodeDiff --staged")
        h.select(screen, "renamed file.txt", "staged")
        h.expect_lines(screen, "original", fixture.files["rename/source file.txt"])
        h.expect_lines(screen, "modified", fixture.files["rename/source file.txt"])
        h.expect_text(screen, "modified", "rename body 2")
        h.idle(screen)
        local before, event = h.panes(screen), h.checkpoint(screen)
        repo.replace("rename/renamed file.txt", 3, "unstaged-rename")
        h.wait_event(screen, event)
        h.preserved(screen, before, 100)
        assert.equals("rename body 2", repo.blob_lines(":0", "rename/renamed file.txt")[3])
      end)

      it("[E15] a deleted preview regains its comparison panes when the file returns", function()
        open("CodeDiff -- gone.txt", "gone.txt")
        h.expect_text(screen, "original", "delete body")
        repo.write_file("gone.txt", { "delete header", "restored body", "delete tail" })
        h.expect_text(screen, "modified", "restored body")
        h.expect_lines(screen, "original", fixture.files["gone.txt"])
        assert.is_nil(screen:exec("return refresh_session().single_side"))
      end)

      it("[E17] hover displays the selected entry's full path without changing the comparison", function()
        open()
        h.panel_cursor(screen, "a.txt", "unstaged")
        local before = h.panes(screen)
        h.action(screen, "explorer", "hover")
        local hover = screen:exec([[
          for _, win in ipairs(vim.api.nvim_list_wins()) do
            if vim.api.nvim_win_get_config(win).relative ~= '' then return win end
          end
        ]])
        assert.is_not_nil(hover)
        screen:await(function()
          return h.window_text(screen, hover) == repo.path("a.txt")
        end, "hover path was not rendered")
        h.action(screen, "explorer", "hover")
        assert.is_false(screen:exec("return vim.api.nvim_win_is_valid(...)", { hover }))
        h.preserved(screen, before, 100)
      end)

      it("[E18] tree navigation skips files inside a collapsed directory", function()
        screen:exec("require('codediff').setup({ explorer = { view_mode = 'tree' } })")
        open("CodeDiff -- nested/alpha.txt nested/deep/beta.txt", "nested/alpha.txt")
        h.action(screen, "view", "next_file", "modified")
        h.expect_text(screen, "modified", "working-beta")
        h.idle(screen)
        h.panel_cursor(screen, "deep", "unstaged")
        h.action(screen, "explorer", "fold_close")
        h.expect_panel(screen, "beta.txt", false)
        h.action(screen, "view", "prev_file", "modified")
        h.expect_text(screen, "modified", "working-alpha")
      end)

      it("[E19] gf opens the working file in the previous tab and the comparison resumes", function()
        open()
        local diff_tab = h.panes(screen).tab
        h.action(screen, "view", "open_in_prev_tab", "original", 2)
        screen:await(function()
          return screen:exec("return vim.api.nvim_get_current_tabpage() ~= (...) and vim.api.nvim_buf_get_name(0) == select(2, ...)", { diff_tab, repo.path("a.txt") })
        end)
        screen:await(function()
          return h.grid_contains(screen, "working-A")
        end)
        screen:command("tabnext")
        h.expect_text(screen, "original", "index-A")
        h.expect_text(screen, "modified", "working-A")
      end)

      it("[E20] double-clicking a panel file selects it through the real mouse mapping", function()
        open()
        h.panel_cursor(screen, "b.txt", "unstaged")
        local p = screen:exec([[
          local win = refresh_session().panel.view.winid
          local pos = vim.api.nvim_win_get_position(win)
          local view = vim.api.nvim_win_call(win, vim.fn.winsaveview)
          return { pos[1] + vim.api.nvim_win_get_cursor(win)[1] - view.topline, pos[2] + 4 }
        ]])
        for _ = 1, 2 do
          screen:request("nvim_input_mouse", { "left", "press", "", 0, p[1], p[2] })
          screen:request("nvim_input_mouse", { "left", "release", "", 0, p[1], p[2] })
        end
        h.expect_text(screen, "modified", "working-B")
      end)

      it("[E16] customized hunk mappings survive replacement of revision buffers", function()
        screen:exec("require('codediff').setup({ keymaps = { view = { next_hunk = '<F6>', stage_hunk = '<F7>' } } })")
        repo.replace("hunks.txt", 1, "working-one")
        repo.replace("hunks.txt", 12, "working-two")
        open("CodeDiff -- hunks.txt", "hunks.txt")
        h.action(screen, "view", "stage_hunk", "modified", 1)
        local original = vim.deepcopy(fixture.files["hunks.txt"])
        original[1] = "working-one"
        h.expect_lines(screen, "original", original)
        h.action(screen, "view", "next_hunk", "original", 1)
        assert.equals(12, screen:exec("return vim.api.nvim_win_get_cursor(0)[1]"))
        h.action(screen, "view", "stage_hunk", "modified", 12)
        screen:await(function()
          return screen:exec("return refresh_session().modified_revision == ':0'")
        end)
        h.action(screen, "view", "next_hunk", "modified", 1)
        h.expect_text(screen, "modified", "working-two")
        assert.equals(12, screen:exec("return vim.api.nvim_win_get_cursor(0)[1]"))
      end)
    end)
  end
end
